### ISSUE TITLE
Invalid context and/or postprocessing for observation collection with complex hasResult

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/ogcapi-sosa#1] opened 2023-09-08 01:46 UTC
As seen here, complex results work happily for observations

https://github.com/opengeospatial/ogcapi-sosa/blob/master/build/tests/unstable/sosa/features/observation/example_2_1.ttl

```
sosa:hasResult [ resultschema:a "r1" ;
            resultschema:b "r2" ] ;
```
But not for observation collections.

https://github.com/opengeospatial/ogcapi-sosa/blob/master/build/tests/unstable/sosa/features/observationCollection/example_1_1.ttl

```
    sosa:hasResult [ ] ;
```

**Comment by avillar** [comment] 2023-09-08 07:57
This is because the single feature has its own ad hoc @context [included in the json example](https://github.com/opengeospatial/ogcapi-sosa/blob/64d77c510b2c446bfa9905f2408e70918528a505/_sources/features/observation/examples/hasResult.json#L2) with terms for the result, while the observation collection doesn't.

**Comment by avillar** [comment] 2023-10-19 10:29
I'm closing this as I'd say it's working as intended (we have no "closure" for JSON-LD contexts). Please reopen if I'm wrong.

**Closed as not planned by avillar** 2023-10-19 10:29 UTC
